apiVersion: v1
kind: ConfigMap
metadata:
  namespace: jenkins
  name: jobs-jcasc
  labels:
    jenkins-jenkins-config: "true"
data:
  jobs.yaml: |
    jobs:
      - script: |
          multibranchPipelineJob('020-proxmox-cloudimg-neomorph-terraform-plan-apply') {
            branchSources {
              git {
                // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
                id('130816114943035757346497006192581719350')
                remote('https://github.com/tuana9a/platform.git')
                includes('rock-n-roll')
              }
            }
            factory {
              workflowBranchProjectFactory {
                scriptPath('.jenkins/020-proxmox-cloudimg-neomorph-terraform-plan-apply.Jenkinsfile')
              }
            }
          }
          multibranchPipelineJob('020-proxmox-cloud-img-terraform-plan-apply') {
            configure {
              it / disabled << 'true'
            }
            branchSources {
              git {
                // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
                id('23655449835313254696393304590131779054')
                remote('https://github.com/tuana9a/platform.git')
                includes('rock-n-roll')
              }
            }
            factory {
              workflowBranchProjectFactory {
                scriptPath('.jenkins/020-proxmox-cloud-img-terraform-plan-apply.Jenkinsfile')
              }
            }
          }
          multibranchPipelineJob('095-github-runners-terraform-plan-apply') {
            branchSources {
              git {
                // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
                id('125764316729195362236712013194236041629')
                remote('https://github.com/tuana9a/platform.git')
                includes('rock-n-roll')
              }
            }
            factory {
              workflowBranchProjectFactory {
                scriptPath('.jenkins/095-github-runners-terraform-plan-apply.Jenkinsfile')
              }
            }
          }
          multibranchPipelineJob('206-github-setup-terraform-plan-apply') {
            branchSources {
              git {
                // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
                id('324648437777820909722399861949115615036')
                remote('https://github.com/tuana9a/platform.git')
                includes('rock-n-roll')
              }
            }
            factory {
              workflowBranchProjectFactory {
                scriptPath('.jenkins/206-github-setup-terraform-plan-apply.Jenkinsfile')
              }
            }
          }
          multibranchPipelineJob('502-coder-postgres-backup') {
            branchSources {
              git {
                // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
                id('252930337889061635601850178896970389690')
                remote('https://github.com/tuana9a/platform.git')
                includes('rock-n-roll')
              }
            }
            factory {
              workflowBranchProjectFactory {
                scriptPath('.jenkins/502-coder-postgres-backup.Jenkinsfile')
              }
            }
          }
          multibranchPipelineJob('511-dkhptd-mongo-backup') {
            configure {
              it / disabled << 'true'
            }
            branchSources {
              git {
                // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
                id('336533647514902334721546031747292855755')
                remote('https://github.com/tuana9a/platform.git')
                includes('rock-n-roll')
              }
            }
            factory {
              workflowBranchProjectFactory {
                scriptPath('.jenkins/511-dkhptd-mongo-backup.Jenkinsfile')
              }
            }
          }
          multibranchPipelineJob('k8s-control-plane-backup-kubernetes') {
            branchSources {
              git {
                // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
                id('284375195950460238746542673225028352947')
                remote('https://github.com/tuana9a/platform.git')
                includes('rock-n-roll')
              }
            }
            factory {
              workflowBranchProjectFactory {
                scriptPath('.jenkins/k8s-control-plane-backup-kubernetes.Jenkinsfile')
              }
            }
          }
          multibranchPipelineJob('k8s-control-plane-etcd-defrag') {
            branchSources {
              git {
                // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
                id('166727458453109288055129079832189105195')
                remote('https://github.com/tuana9a/platform.git')
                includes('rock-n-roll')
              }
            }
            factory {
              workflowBranchProjectFactory {
                scriptPath('.jenkins/k8s-control-plane-etcd-defrag.Jenkinsfile')
              }
            }
          }
          multibranchPipelineJob('TerraformPlanApplyNotify') {
            branchSources {
              git {
                // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
                id('211093900555508930013598879081077991228')
                remote('https://github.com/tuana9a/platform.git')
                includes('rock-n-roll')
              }
            }
            factory {
              workflowBranchProjectFactory {
                scriptPath('.jenkins/TerraformPlanApplyNotify.Jenkinsfile')
              }
            }
          }
          multibranchPipelineJob('test-aws-oidc') {
            branchSources {
              git {
                // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
                id('163954511379159881132487778335510043698')
                remote('https://github.com/tuana9a/platform.git')
                includes('rock-n-roll')
              }
            }
            factory {
              workflowBranchProjectFactory {
                scriptPath('.jenkins/test-aws-oidc.Jenkinsfile')
              }
            }
          }
          multibranchPipelineJob('test-gcp-oidc') {
            branchSources {
              git {
                // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
                id('287402406923296937009564441310602818497')
                remote('https://github.com/tuana9a/platform.git')
                includes('rock-n-roll')
              }
            }
            factory {
              workflowBranchProjectFactory {
                scriptPath('.jenkins/test-gcp-oidc.Jenkinsfile')
              }
            }
          }
          multibranchPipelineJob('test') {
            branchSources {
              git {
                // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
                id('12707736894140473154801792860916528374')
                remote('https://github.com/tuana9a/platform.git')
                includes('rock-n-roll')
              }
            }
            factory {
              workflowBranchProjectFactory {
                scriptPath('.jenkins/test.Jenkinsfile')
              }
            }
          }
          multibranchPipelineJob('vault-backup') {
            branchSources {
              git {
                // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
                id('67757721893216528638919868102691056770')
                remote('https://github.com/tuana9a/platform.git')
                includes('rock-n-roll')
              }
            }
            factory {
              workflowBranchProjectFactory {
                scriptPath('.jenkins/vault-backup.Jenkinsfile')
              }
            }
          }
          multibranchPipelineJob('vault-secret-store-token-renew') {
            branchSources {
              git {
                // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
                id('60046855633295167470940976125235051245')
                remote('https://github.com/tuana9a/platform.git')
                includes('rock-n-roll')
              }
            }
            factory {
              workflowBranchProjectFactory {
                scriptPath('.jenkins/vault-secret-store-token-renew.Jenkinsfile')
              }
            }
          }
          multibranchPipelineJob('vault-unseal') {
            branchSources {
              git {
                // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
                id('30604091230084558390226995134000180900')
                remote('https://github.com/tuana9a/platform.git')
                includes('rock-n-roll')
              }
            }
            factory {
              workflowBranchProjectFactory {
                scriptPath('.jenkins/vault-unseal.Jenkinsfile')
              }
            }
          }
