apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: coder
  name: coder-env
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-tuana9a-com
    kind: ClusterSecretStore
  target:
    name: coder-env
  dataFrom:
    - extract:
        key: coder/env
