apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: coder
  name: postgres-env
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-tuana9a-com
    kind: ClusterSecretStore
  target:
    name: postgres-env
  dataFrom:
    - extract:
        key: coder/postgres/env
