- shell: |
    set -xeu
    sudo kubeadm upgrade plan
  register: kubeadm_upgrade_plan
- debug:
    msg: "{{ kubeadm_upgrade_plan.stdout_lines }}"

- name: apply upgrades
  shell: |
    set -xeu
    sudo kubeadm upgrade apply v{{ kubernetes_minor_version }} -y
  register: apply_upgrade
- debug:
    msg: "{{ apply_upgrade.stdout_lines }}"
