- name: upgrade kubeadm
  shell: |
    set -xeu
    sudo apt-mark unhold kubeadm
    sudo apt-get update && sudo apt-get install -y kubeadm='{{ kubernetes_version_minor }}-*'
    sudo apt-mark hold kubeadm
    kubeadm version
  register: upgrade_kubeadm
- debug:
    msg: "{{ upgrade_kubeadm.stdout | split('\n') }}"
