- name: upgrade kubelet kubectl
  shell: |
    set -xeu
    sudo apt-mark unhold kubelet kubectl
    sudo apt-get update && sudo apt-get install -y kubelet='{{ kubernetes_version_minor }}-*' kubectl='{{ kubernetes_version_minor }}-*'
    sudo apt-mark hold kubelet kubectl
  register: kubelet_kubectl_upgrade
- debug:
    msg: "{{ kubelet_kubectl_upgrade.stdout_lines }}"

- name: restart kubelet
  shell: |
    set -xeu
    sudo systemctl daemon-reload
    sudo systemctl restart kubelet
