- name: Download containerd archive
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/containerd/containerd/releases/download/v1.7.24/containerd-1.7.24-linux-amd64.tar.gz"
    dest: "/opt/containerd-1.7.24-linux-amd64.tar.gz"
    mode: "0644"

- name: Extract containerd to /usr/local
  become: true
  ansible.builtin.unarchive:
    src: "/opt/containerd-1.7.24-linux-amd64.tar.gz"
    dest: "/usr/local"
    remote_src: yes
    # Optimization: prevents re-extraction if the main binary exists
    creates: "/usr/local/bin/containerd"

- name: Create containerd directory
  become: true
  ansible.builtin.file:
    path: "/etc/containerd"
    state: directory
    mode: "0755"

- name: write containerd.service file
  become: true
  ansible.builtin.template:
    src: templates/containerd.service
    dest: /lib/systemd/system/containerd.service
    owner: root
    group: root
    mode: "0644"

- name: write containerd config.toml file
  become: true
  ansible.builtin.template:
    src: templates/containerd/config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: "0644"

- name: start and enable containerd.service
  become: true
  ansible.builtin.systemd_service:
    name: containerd
    state: started
    enabled: true
    daemon_reload: true
