- name: Apply ufw firewall rules
  become: true
  loop: "{{ ufw_rules }}"
  community.general.ufw:
    rule: "{{ item.rule }}"
    from_ip: "{{ item.from_ip | default('any') }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.name }}"
    delete: "{{ item.delete | default(false) }}"
  when: "ufw_state == 'enabled'"

- name: Enable/Disable ufw
  become: true
  community.general.ufw:
    state: "{{ ufw_state }}"
