- name: /etc/cron.d/wireguard_heartbeats
  become: true
  ansible.builtin.template:
    # We reference the template file we will create below
    src: wireguard_heartbeats.j2
    dest: /etc/cron.d/wireguard_heartbeats
    owner: root
    group: root
    mode: "0644"
    backup: yes
  # Note: The 'wireguard_heartbeats' variable must be defined
  # as an array in your playbook or inventory, e.g.:
  # wireguard_heartbeats:
  #   - 10.0.0.2
  #   - 10.0.0.3
  #   - 10.0.0.4
