apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 698-prometheus-scrape-targets
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 10
  source:
    path: 698-prometheus-scrape-targets
    repoURL: https://github.com/tuana9a/platform.git
    targetRevision: rock-n-roll
  destination:
    server: https://kubernetes.default.svc.cluster.local
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
