apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: prometheus
  name: alertmanager
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-tuana9a-com
    kind: ClusterSecretStore
  target:
    name: alertmanager
  dataFrom:
    - extract:
        key: prometheus/alertmanager
