persistence:
  storageClass: proxmox-data-xfs
  size: 5Gi
config:
  enabled: true
  route:
    receiver: "telegram"
  receivers:
    - name: "telegram"
      telegram_configs:
        - bot_token_file: /etc/telegram_bot_token.txt
          chat_id: -1002012523352 # t9st group
extraSecretMounts:
  - name: telegram-bot-token
    mountPath: /etc/telegram_bot_token.txt
    subPath: telegram_bot_token.txt
    secretName: alertmanager
    readOnly: true
