apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-tuana9a-com
spec:
  provider:
    vault:
      server: "https://vault.tuana9a.com"
      path: "kv"
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: "v1"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          namespace: vault
          name: "clustersecretstore-vault-tuana9a-com"
          key: "VAULT_TOKEN"
