apiVersion: v1
kind: Service
metadata:
  namespace: prometheus
  name: external-node-exporter
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: prometheus
  name: external-node-exporter
subsets:
  - addresses:
      - ip: "192.168.1.112" # neo
      - ip: "192.168.56.7" # nfs
      - ip: "192.168.56.209" # dev2
      - ip: "14.225.1.214" # orisis
      - ip: "103.232.121.190" # xeno
    ports:
      - port: 9100
        protocol: TCP
