name: "025-ecr-tuana9a"

on:
  workflow_dispatch:
  push:
    paths:
      - "025-ecr-tuana9a/**"
      - ".github/workflows/025-ecr-tuana9a*"
    branches:
      - rock-n-roll

jobs:
  main:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/terraform-plan-apply-notify.yml
    with:
      WORKING_DIR: ${{ github.workflow }}
      setup-aws: true
      AWS_ASSUME_ROLE: arn:aws:iam::384588864907:role/terraform-ecr-admin
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
