name: "031-gcp-network-nat-tuana9a"

on:
  workflow_dispatch:
  push:
    paths:
      - "031-gcp-network-nat-tuana9a/**"
      - ".github/workflows/031-gcp-network-nat-tuana9a*"
    branches:
      - rock-n-roll

jobs:
  main:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/terraform-plan-apply-notify.yml
    with:
      WORKING_DIR: ${{ github.workflow }}
      GCP_SERVICE_ACCOUNT: terraform-network-admin@tuana9a.iam.gserviceaccount.com
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
