name: "085-spegel"

on:
  workflow_dispatch:
  push:
    paths:
      - "085-spegel/**"
      - ".github/workflows/085-spegel-terraform-plan-apply*"
    branches:
      - rock-n-roll

jobs:
  main:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/terraform-plan-apply-notify.yml
    with:
      runs-on: self-hosted-0
      WORKING_DIR: ${{ github.workflow }}
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
