name: "150-metrics-server"

on:
  workflow_dispatch:
  push:
    paths:
      - "150-metrics-server/**"
      - ".github/workflows/150-metrics-server-terraform-plan-apply*"
    branches:
      - rock-n-roll

jobs:
  main:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/terraform-plan-apply-notify.yml
    with:
      runs-on: self-hosted-0
      WORKING_DIR: ${{ github.workflow }}
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
