name: "300-loki"

on:
  workflow_dispatch:
  push:
    paths:
      - "300-loki/**"
      - ".github/workflows/300-loki-terraform-plan-apply*"
    branches:
      - rock-n-roll

jobs:
  main:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/TerraformPlanApplyNotify.yml
    with:
      runs-on: self-hosted-0
      WORKING_DIR: ${{ github.workflow }}
      setup-aws: true
      AWS_ASSUME_ROLE: arn:aws:iam::384588864907:role/i-300-loki
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
